# Copyright (c) 2017-2025 The Khronos Group Inc.
#
# SPDX-License-Identifier: Apache-2.0

version: 1.1.52.{build}
image: Visual Studio 2017


environment:
  VULKAN_SDK: c:\VulkanSDK\1.1.114.0
  VKSDKURL: https://people.collabora.com/~rpavlik/ci_resources/vksdk-1.1.114.0-lite.7z
  VKSDKPKG: c:\VulkanSDK\vksdk-1.1.114.0-lite.7z
  matrix:
# 32-bit
    - VCVARS: vcvarsamd64_x86
      VCPKG_PLATFORM: x86-windows
# 64-bit
    - VCVARS: vcvars64
      VCPKG_PLATFORM: x64-windows

matrix:
  fast_finish: true # finish immediately once one of the jobs fails

# fetch repository as zip archive
shallow_clone: true                 # default is "false"


cache:
  - c:\VulkanSDK\1.1.114.0
install:
  - choco install -y ninja
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # Download and extract a stripped-down Vulkan SDK if not cached - the "Start-Process" is to not continue until extraction is done
  - ps: >-
      if (-not (Test-Path "$env:VULKAN_SDK/Include/vulkan/vulkan.h")) {
        mkdir c:\VulkanSDK
        $wc = New-Object System.Net.WebClient
        $wc.DownloadFile($env:VKSDKURL, $env:VKSDKPKG)
        Start-Process "c:\Program Files\7-Zip\7z" -ArgumentList "x", $env:VKSDKPKG, "-oC:\VulkanSDK" -Wait
      }

# for future use if we need vcpkg
# -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake

build_script:
- cmd: >-
    call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\%VCVARS%.bat" &&
    cmake -GNinja -Bbuild -H. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPython3_EXECUTABLE=C:/Python37-x64/python.exe -DBUILD_ALL_EXTENSIONS=ON &&
    ninja -C build
- cmd: >-
    call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\%VCVARS%.bat" &&
    cmake -GNinja -Bbuild -H. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DDYNAMIC_LOADER=ON -DPython3_EXECUTABLE=C:/Python37-x64/python.exe -DBUILD_ALL_EXTENSIONS=ON &&
    ninja -C build
